// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutoStartService is the Wails service that exposes login-item auto-start
 * registration to the frontend (issue #45).
 * 
 * It deliberately owns only the OS registration: persistence of the
 * AutoStartOnLogin preference belongs to ConfigService, so an OS-level
 * registration failure must not fail the settings save. Such failures are
 * therefore returned as a human-readable warning string with a nil error;
 * the error return is reserved for internal cases (e.g. an unwired backend).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * IsAutoStartEnabled reports the ACTUAL OS registration state (not the
 * persisted preference). With no backend wired it returns (false, error).
 */
export function IsAutoStartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2421906010);
}

/**
 * SetAutoStart registers (true) or removes (false) the login item with the
 * OS. On success it returns ("", nil). OS failures come back as a non-empty
 * human warning string with a nil error so the caller-owned settings save is
 * never failed by the registration step; the error return is reserved for
 * the internal unwired-backend case, which is also reported as a warning
 * rather than an error to keep the frontend flow simple.
 */
export function SetAutoStart(enabled: boolean): $CancellablePromise<string> {
    return $Call.ByID(1771376721, enabled);
}
