// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSecret removes a secret from the keyring and drops its reference
 * from the YAML file. If the key is not present in the keyring, it is
 * ignored (silent non-error).
 */
export function DeleteSecret(ref: string): $CancellablePromise<void> {
    return $Call.ByID(1277217372, ref);
}

/**
 * GetKeyringServiceName returns the service name used when storing secrets
 * in the OS keyring.
 */
export function GetKeyringServiceName(): $CancellablePromise<string> {
    return $Call.ByID(3689252326);
}

/**
 * GetSecret retrieves a secret value from the keyring. It returns the
 * sentinel errNotFound if the key does not exist.
 */
export function GetSecret(ref: string): $CancellablePromise<string> {
    return $Call.ByID(2719136585, ref);
}

/**
 * IsKeyringAvailable reports whether the underlying keyring implementation
 * is available on the host.
 */
export function IsKeyringAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(2023583063);
}

/**
 * LoadSettings loads the configuration from disk and merges defaults.
 */
export function LoadSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3950522526);
}

/**
 * SaveSettings writes the Settings to disk. If the Settings contain any
 * secrets and the keyring is unavailable, it fails early with the hard-fail
 * error before touching any filesystem. On success, the secret values are
 * stripped from the YAML, and the secret references are stored under
 * SecretRefs only. The returned bool reports whether the keyring is
 * available, so the UI can warn the user even when no secrets are present.
 */
export function SaveSettings(s: $models.Settings): $CancellablePromise<boolean> {
    return $Call.ByID(298700571, s);
}

/**
 * SetSecret stores a secret value under the given reference. It performs a
 * hard-fail check against keyring availability and writes to the keyring.
 */
export function SetSecret(ref: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1903009237, ref, value);
}

/**
 * ValidateSecretRefs ensures that all keys present in SecretRefs are within
 * the known set of acceptable references.
 */
export function ValidateSecretRefs(s: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(1128019623, s);
}
