// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSecret removes a secret from the keyring and drops its reference
 * from the YAML file. If the key is not present in the keyring, it is
 * ignored (silent non-error).
 * @param {string} ref
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSecret(ref) {
    return $Call.ByID(1277217372, ref);
}

/**
 * GetKeyringServiceName returns the service name used when storing secrets
 * in the OS keyring.
 * @returns {$CancellablePromise<string>}
 */
export function GetKeyringServiceName() {
    return $Call.ByID(3689252326);
}

/**
 * GetSecret retrieves a secret value from the keyring. It returns the
 * sentinel errNotFound if the key does not exist.
 * @param {string} ref
 * @returns {$CancellablePromise<string>}
 */
export function GetSecret(ref) {
    return $Call.ByID(2719136585, ref);
}

/**
 * IsKeyringAvailable reports whether the underlying keyring implementation
 * is available on the host.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsKeyringAvailable() {
    return $Call.ByID(2023583063);
}

/**
 * LoadSettings loads the configuration from disk and merges defaults.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function LoadSettings() {
    return $Call.ByID(3950522526).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveSettings writes the Settings to disk. If the Settings contain any
 * secrets and the keyring is unavailable, it fails early with the hard-fail
 * error before touching any filesystem. On success, the secret values are
 * stripped from the YAML, and the secret references are stored under
 * SecretRefs only. The returned bool reports whether the keyring is
 * available, so the UI can warn the user even when no secrets are present.
 * @param {$models.Settings} s
 * @returns {$CancellablePromise<boolean>}
 */
export function SaveSettings(s) {
    return $Call.ByID(298700571, s);
}

/**
 * SetSecret stores a secret value under the given reference. It performs a
 * hard-fail check against keyring availability and writes to the keyring.
 * @param {string} ref
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSecret(ref, value) {
    return $Call.ByID(1903009237, ref, value);
}

/**
 * @param {$models.Supervisor | null} sv
 * @returns {$CancellablePromise<void>}
 */
export function SetSupervisor(sv) {
    return $Call.ByID(1294203747, sv);
}

/**
 * ValidateSecretRefs ensures that all keys present in SecretRefs are within
 * the known set of acceptable references.
 * @param {$models.Settings} s
 * @returns {$CancellablePromise<void>}
 */
export function ValidateSecretRefs(s) {
    return $Call.ByID(1128019623, s);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
