// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkerView is the slim projection the desktop UI renders. It mirrors
 * router.WorkerInfo (the /v1/workers projection) but adds a friendly
 * relative "last seen" string computed client-side.
 */
export interface WorkerView {
    "id": string;
    "hostname": string;
    "ip": string;
    "port": number;
    "status": string;
    "version": string;
    "loaded_models": string[] | null;
    "last_seen": string;

    /**
     * LastSeenRel is "3s ago" / "just now" — derived from LastSeen at render time.
     */
    "last_seen_rel": string;

    /**
     * Address is "host:port" for the card title.
     */
    "address": string;
}
