// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PopularModelView is the UI projection of router.PopularModelInfo. Field
 * names mirror the router JSON tags exactly so the generated Wails binding
 * is a straight pass-through.
 */
export class PopularModelView {
    /**
     * Creates a new PopularModelView instance.
     * @param {Partial<PopularModelView>} [$$source = {}] - The source object to create the PopularModelView.
     */
    constructor($$source = {}) {
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("worker_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["worker_count"] = 0;
        }
        if (!("loaded_worker_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["loaded_worker_count"] = 0;
        }
        if (!("call_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["call_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PopularModelView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PopularModelView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PopularModelView(/** @type {Partial<PopularModelView>} */($$parsedSource));
    }
}

/**
 * ProcessState is the lifecycle state of a supervised child process.
 * @readonly
 * @enum {string}
 */
export const ProcessState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * StateStopped means the process is not running (never started, exited on
     * its own, or was stopped by the user).
     */
    StateStopped: "stopped",

    /**
     * StateRunning means the child is up and listening.
     */
    StateRunning: "running",

    /**
     * StateError means the process failed to start or exited abnormally.
     */
    StateError: "error",
};

/**
 * ProcessStatus is the UI projection of one supervised child process.
 */
export class ProcessStatus {
    /**
     * Creates a new ProcessStatus instance.
     * @param {Partial<ProcessStatus>} [$$source = {}] - The source object to create the ProcessStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {ProcessState}
             */
            this["state"] = ProcessState.$zero;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("healthy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["healthy"] = false;
        }
        if (!("registered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["registered"] = false;
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["log_path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessStatus(/** @type {Partial<ProcessStatus>} */($$parsedSource));
    }
}

/**
 * Settings holds non-secret configuration options plus secret references and
 * values. The "yaml\"-\" tag on Secrets is literal: never include the actual
 * secret value in the YAML file. The secret_refs field is used instead to
 * reference a secret managed by the Keyring.
 * nolint:tagalign
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("router_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["router_addr"] = "";
        }
        if (!("router_apikey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["router_apikey"] = "";
        }
        if (!("router_binary_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["router_binary_path"] = "";
        }
        if (!("worker_addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worker_addr"] = "";
        }
        if (!("worker_apikey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worker_apikey"] = "";
        }
        if (!("worker_backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worker_backend"] = "";
        }
        if (!("worker_model_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worker_model_path"] = "";
        }
        if (!("worker_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["worker_port"] = 0;
        }
        if (!("worker_binary_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worker_binary_path"] = "";
        }
        if (!("worker_custom_auth" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worker_custom_auth"] = "";
        }
        if (!("worker_enable_health_checks" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["worker_enable_health_checks"] = null;
        }
        if (!("worker_mtls_cert" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worker_mtls_cert"] = "";
        }
        if (!("worker_mtls_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["worker_mtls_key"] = "";
        }
        if (!("relay_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relay_url"] = "";
        }
        if (!("model_aliases" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["model_aliases"] = {};
        }
        if (!("dev_mode" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["dev_mode"] = null;
        }
        if (!("auto_start_on_login" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["auto_start_on_login"] = null;
        }
        if (!("secrets" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["secrets"] = {};
        }
        if (!("secret_refs" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["secret_refs"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType0;
        const $$createField17_0 = $$createType0;
        const $$createField18_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("model_aliases" in $$parsedSource) {
            $$parsedSource["model_aliases"] = $$createField14_0($$parsedSource["model_aliases"]);
        }
        if ("secrets" in $$parsedSource) {
            $$parsedSource["secrets"] = $$createField17_0($$parsedSource["secrets"]);
        }
        if ("secret_refs" in $$parsedSource) {
            $$parsedSource["secret_refs"] = $$createField18_0($$parsedSource["secret_refs"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * Supervisor is a Wails service that launches and manages the headless
 * router/worker binaries on behalf of the desktop app (issue #44).
 * 
 * Wails-bound methods: StartRouter / StopRouter / StartWorker / StopWorker
 * / Status / RestartRouter / RestartWorker.
 * 
 * Secrets: the supervisor never holds secret values directly. When building
 * child process args it resolves secrets from the keyring (router/apikey for
 * --api-key, mtls/cert + mtls/key for --mtls-cert/--mtls-key) and never logs
 * them. Dev mode (the default) requires no secrets.
 */
export class Supervisor {
    /**
     * Creates a new Supervisor instance.
     * @param {Partial<Supervisor>} [$$source = {}] - The source object to create the Supervisor.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Supervisor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Supervisor}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Supervisor(/** @type {Partial<Supervisor>} */($$parsedSource));
    }
}

/**
 * SupervisorStatus is the full status returned by Supervisor.Status().
 */
export class SupervisorStatus {
    /**
     * Creates a new SupervisorStatus instance.
     * @param {Partial<SupervisorStatus>} [$$source = {}] - The source object to create the SupervisorStatus.
     */
    constructor($$source = {}) {
        if (!("router" in $$source)) {
            /**
             * @member
             * @type {ProcessStatus}
             */
            this["router"] = (new ProcessStatus());
        }
        if (!("worker" in $$source)) {
            /**
             * @member
             * @type {ProcessStatus}
             */
            this["worker"] = (new ProcessStatus());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["router_url"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupervisorStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SupervisorStatus}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("router" in $$parsedSource) {
            $$parsedSource["router"] = $$createField0_0($$parsedSource["router"]);
        }
        if ("worker" in $$parsedSource) {
            $$parsedSource["worker"] = $$createField1_0($$parsedSource["worker"]);
        }
        return new SupervisorStatus(/** @type {Partial<SupervisorStatus>} */($$parsedSource));
    }
}

/**
 * WorkerView is the slim projection the desktop UI renders. It mirrors
 * router.WorkerInfo (the /v1/workers projection) but adds a friendly
 * relative "last seen" string computed client-side.
 */
export class WorkerView {
    /**
     * Creates a new WorkerView instance.
     * @param {Partial<WorkerView>} [$$source = {}] - The source object to create the WorkerView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("loaded_models" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["loaded_models"] = [];
        }
        if (!("last_seen" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_seen"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("last_seen_rel" in $$source)) {
            /**
             * LastSeenRel is "3s ago" / "just now" — derived from LastSeen at render time.
             * @member
             * @type {string}
             */
            this["last_seen_rel"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * Address is "host:port" for the card title.
             * @member
             * @type {string}
             */
            this["address"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkerView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkerView}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("loaded_models" in $$parsedSource) {
            $$parsedSource["loaded_models"] = $$createField6_0($$parsedSource["loaded_models"]);
        }
        return new WorkerView(/** @type {Partial<WorkerView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ProcessStatus.createFrom;
const $$createType2 = $Create.Array($Create.Any);
