// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PopularModelView is the UI projection of router.PopularModelInfo. Field
 * names mirror the router JSON tags exactly so the generated Wails binding
 * is a straight pass-through.
 */
export class PopularModelView {
    "model": string;
    "worker_count": number;
    "loaded_worker_count": number;
    "call_count": number;

    /** Creates a new PopularModelView instance. */
    constructor($$source: Partial<PopularModelView> = {}) {
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("worker_count" in $$source)) {
            this["worker_count"] = 0;
        }
        if (!("loaded_worker_count" in $$source)) {
            this["loaded_worker_count"] = 0;
        }
        if (!("call_count" in $$source)) {
            this["call_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PopularModelView instance from a string or object.
     */
    static createFrom($$source: any = {}): PopularModelView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PopularModelView($$parsedSource as Partial<PopularModelView>);
    }
}

/**
 * ProcessState is the lifecycle state of a supervised child process.
 */
export enum ProcessState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StateStopped means the process is not running (never started, exited on
     * its own, or was stopped by the user).
     */
    StateStopped = "stopped",

    /**
     * StateRunning means the child is up and listening.
     */
    StateRunning = "running",

    /**
     * StateError means the process failed to start or exited abnormally.
     */
    StateError = "error",
};

/**
 * ProcessStatus is the UI projection of one supervised child process.
 */
export class ProcessStatus {
    "state": ProcessState;
    "running": boolean;
    "healthy": boolean;
    "registered": boolean;
    "pid": number;
    "started_at": string;
    "log_path"?: string;
    "error"?: string;

    /** Creates a new ProcessStatus instance. */
    constructor($$source: Partial<ProcessStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = ProcessState.$zero;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("healthy" in $$source)) {
            this["healthy"] = false;
        }
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessStatus($$parsedSource as Partial<ProcessStatus>);
    }
}

/**
 * Settings holds non-secret configuration options plus secret references and
 * values. The "yaml\"-\" tag on Secrets is literal: never include the actual
 * secret value in the YAML file. The secret_refs field is used instead to
 * reference a secret managed by the Keyring.
 * nolint:tagalign
 */
export class Settings {
    "router_addr": string;
    "router_apikey": string;
    "router_binary_path": string;
    "worker_addr": string;
    "worker_apikey": string;
    "worker_backend": string;
    "worker_model_path": string;
    "worker_port": number;
    "worker_binary_path": string;
    "worker_custom_auth": string;
    "worker_enable_health_checks": boolean | null;
    "worker_mtls_cert": string;
    "worker_mtls_key": string;
    "relay_url": string;
    "dev_mode": boolean | null;
    "auto_start_on_login": boolean | null;
    "secrets": { [_ in string]?: string };
    "secret_refs": { [_ in string]?: string };

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("router_addr" in $$source)) {
            this["router_addr"] = "";
        }
        if (!("router_apikey" in $$source)) {
            this["router_apikey"] = "";
        }
        if (!("router_binary_path" in $$source)) {
            this["router_binary_path"] = "";
        }
        if (!("worker_addr" in $$source)) {
            this["worker_addr"] = "";
        }
        if (!("worker_apikey" in $$source)) {
            this["worker_apikey"] = "";
        }
        if (!("worker_backend" in $$source)) {
            this["worker_backend"] = "";
        }
        if (!("worker_model_path" in $$source)) {
            this["worker_model_path"] = "";
        }
        if (!("worker_port" in $$source)) {
            this["worker_port"] = 0;
        }
        if (!("worker_binary_path" in $$source)) {
            this["worker_binary_path"] = "";
        }
        if (!("worker_custom_auth" in $$source)) {
            this["worker_custom_auth"] = "";
        }
        if (!("worker_enable_health_checks" in $$source)) {
            this["worker_enable_health_checks"] = null;
        }
        if (!("worker_mtls_cert" in $$source)) {
            this["worker_mtls_cert"] = "";
        }
        if (!("worker_mtls_key" in $$source)) {
            this["worker_mtls_key"] = "";
        }
        if (!("relay_url" in $$source)) {
            this["relay_url"] = "";
        }
        if (!("dev_mode" in $$source)) {
            this["dev_mode"] = null;
        }
        if (!("auto_start_on_login" in $$source)) {
            this["auto_start_on_login"] = null;
        }
        if (!("secrets" in $$source)) {
            this["secrets"] = {};
        }
        if (!("secret_refs" in $$source)) {
            this["secret_refs"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField16_0 = $$createType0;
        const $$createField17_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("secrets" in $$parsedSource) {
            $$parsedSource["secrets"] = $$createField16_0($$parsedSource["secrets"]);
        }
        if ("secret_refs" in $$parsedSource) {
            $$parsedSource["secret_refs"] = $$createField17_0($$parsedSource["secret_refs"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * Supervisor is a Wails service that launches and manages the headless
 * router/worker binaries on behalf of the desktop app (issue #44).
 * 
 * Wails-bound methods: StartRouter / StopRouter / StartWorker / StopWorker
 * / Status / RestartRouter / RestartWorker.
 * 
 * Secrets: the supervisor never holds secret values directly. When building
 * child process args it resolves secrets from the keyring (router/apikey for
 * --api-key, mtls/cert + mtls/key for --mtls-cert/--mtls-key) and never logs
 * them. Dev mode (the default) requires no secrets.
 */
export class Supervisor {

    /** Creates a new Supervisor instance. */
    constructor($$source: Partial<Supervisor> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Supervisor instance from a string or object.
     */
    static createFrom($$source: any = {}): Supervisor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Supervisor($$parsedSource as Partial<Supervisor>);
    }
}

/**
 * SupervisorStatus is the full status returned by Supervisor.Status().
 */
export class SupervisorStatus {
    "router": ProcessStatus;
    "worker": ProcessStatus;
    "router_url"?: string;

    /** Creates a new SupervisorStatus instance. */
    constructor($$source: Partial<SupervisorStatus> = {}) {
        if (!("router" in $$source)) {
            this["router"] = (new ProcessStatus());
        }
        if (!("worker" in $$source)) {
            this["worker"] = (new ProcessStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupervisorStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SupervisorStatus {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("router" in $$parsedSource) {
            $$parsedSource["router"] = $$createField0_0($$parsedSource["router"]);
        }
        if ("worker" in $$parsedSource) {
            $$parsedSource["worker"] = $$createField1_0($$parsedSource["worker"]);
        }
        return new SupervisorStatus($$parsedSource as Partial<SupervisorStatus>);
    }
}

/**
 * WorkerView is the slim projection the desktop UI renders. It mirrors
 * router.WorkerInfo (the /v1/workers projection) but adds a friendly
 * relative "last seen" string computed client-side.
 */
export class WorkerView {
    "id": string;
    "hostname": string;
    "ip": string;
    "port": number;
    "status": string;
    "version": string;
    "loaded_models": string[];
    "last_seen": string;

    /**
     * LastSeenRel is "3s ago" / "just now" — derived from LastSeen at render time.
     */
    "last_seen_rel": string;

    /**
     * Address is "host:port" for the card title.
     */
    "address": string;

    /** Creates a new WorkerView instance. */
    constructor($$source: Partial<WorkerView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("loaded_models" in $$source)) {
            this["loaded_models"] = [];
        }
        if (!("last_seen" in $$source)) {
            this["last_seen"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("last_seen_rel" in $$source)) {
            this["last_seen_rel"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkerView instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkerView {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("loaded_models" in $$parsedSource) {
            $$parsedSource["loaded_models"] = $$createField6_0($$parsedSource["loaded_models"]);
        }
        return new WorkerView($$parsedSource as Partial<WorkerView>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ProcessStatus.createFrom;
const $$createType2 = $Create.Array($Create.Any);
