// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings holds non-secret configuration options plus secret references and
 * values. The "yaml\"-\" tag on Secrets is literal: never include the actual
 * secret value in the YAML file. The secret_refs field is used instead to
 * reference a secret managed by the Keyring.
 * nolint:tagalign
 */
export interface Settings {
    "router_addr": string;
    "router_apikey": string;
    "worker_addr": string;
    "worker_apikey": string;
    "worker_backend": string;
    "worker_model_path": string;
    "worker_port": number;
    "worker_custom_auth": string;
    "worker_enable_health_checks": boolean | null;
    "worker_mtls_cert": string;
    "worker_mtls_key": string;
    "relay_url": string;
    "dev_mode": boolean | null;
    "secrets": { [_ in string]?: string } | null;
    "secret_refs": { [_ in string]?: string } | null;
}

/**
 * WorkerView is the slim projection the desktop UI renders. It mirrors
 * router.WorkerInfo (the /v1/workers projection) but adds a friendly
 * relative "last seen" string computed client-side.
 */
export interface WorkerView {
    "id": string;
    "hostname": string;
    "ip": string;
    "port": number;
    "status": string;
    "version": string;
    "loaded_models": string[] | null;
    "last_seen": string;

    /**
     * LastSeenRel is "3s ago" / "just now" — derived from LastSeen at render time.
     */
    "last_seen_rel": string;

    /**
     * Address is "host:port" for the card title.
     */
    "address": string;
}
