// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RouterClient is a Wails service bound to the frontend. It talks to the
 * router's HTTP API over plain HTTP (dev mode). No auth, no mTLS here —
 * that is prod-mode scope (#9/#10), not the desktop MVP.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetRouterURL returns the configured base URL (used by the UI to show the
 * unreachable-router error card).
 */
export function GetRouterURL(): $CancellablePromise<string> {
    return $Call.ByID(511773612);
}

/**
 * GetWorkers fetches the connected-workers list from the router. It returns
 * an empty (non-nil) slice when the router is reachable but idle, and a
 * typed error when the router is unreachable or returns a bad body.
 */
export function GetWorkers(): $CancellablePromise<$models.WorkerView[] | null> {
    return $Call.ByID(207224501);
}

/**
 * SetRouterURL re-points the client to a new router base URL. It is safe to
 * call at any time; subsequent GetWorkers() calls use the new URL. An empty
 * or malformed url falls back to defaultRouterURL (same normalisation as the
 * constructor). Does NOT persist to disk — that is the ConfigService's job.
 */
export function SetRouterURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(1269668880, url);
}
