// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Supervisor is a Wails service that launches and manages the headless
 * router/worker binaries on behalf of the desktop app (issue #44).
 * 
 * Wails-bound methods: StartRouter / StopRouter / StartWorker / StopWorker
 * / Status / RestartRouter / RestartWorker.
 * 
 * Secrets: the supervisor never holds secret values directly. When building
 * child process args it resolves secrets from the keyring (router/apikey for
 * --api-key, mtls/cert + mtls/key for --mtls-cert/--mtls-key) and never logs
 * them. Dev mode (the default) requires no secrets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * IsRouterRunning reports whether the router child is alive.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRouterRunning() {
    return $Call.ByID(163630674);
}

/**
 * IsWorkerRunning reports whether the worker child is alive.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsWorkerRunning() {
    return $Call.ByID(3020673067);
}

/**
 * RestartRouter stops then starts the router.
 * @returns {$CancellablePromise<void>}
 */
export function RestartRouter() {
    return $Call.ByID(2573138224);
}

/**
 * RestartWorker stops then starts the worker.
 * @returns {$CancellablePromise<void>}
 */
export function RestartWorker() {
    return $Call.ByID(1439454907);
}

/**
 * StartRouter launches the router binary from the saved config. It resolves
 * secrets from the keyring only when running in prod mode; dev mode needs none.
 * @returns {$CancellablePromise<void>}
 */
export function StartRouter() {
    return $Call.ByID(3710000223);
}

/**
 * StartWorker launches the worker binary from the saved config.
 * @returns {$CancellablePromise<void>}
 */
export function StartWorker() {
    return $Call.ByID(286835744);
}

/**
 * Status reports the current state of both supervised children plus a live
 * health probe against the router (which also yields the worker-registration
 * list). It never errors: an unreachable router simply reads as unhealthy.
 * @returns {$CancellablePromise<$models.SupervisorStatus>}
 */
export function Status() {
    return $Call.ByID(3064718224).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StopAll stops both children and removes temp files. Intended for use on
 * application shutdown.
 * @returns {$CancellablePromise<void>}
 */
export function StopAll() {
    return $Call.ByID(3237043877);
}

/**
 * StopRouter stops the router child (graceful SIGTERM → SIGKILL). Returns nil
 * if the router was not running.
 * @returns {$CancellablePromise<void>}
 */
export function StopRouter() {
    return $Call.ByID(3674121687);
}

/**
 * StopWorker stops the worker child. Returns nil if not running.
 * @returns {$CancellablePromise<void>}
 */
export function StopWorker() {
    return $Call.ByID(2057410952);
}

// Private type creation functions
const $$createType0 = $models.SupervisorStatus.createFrom;
