// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Supervisor is a Wails service that launches and manages the headless
 * router/worker binaries on behalf of the desktop app (issue #44).
 * 
 * Wails-bound methods: StartRouter / StopRouter / StartWorker / StopWorker
 * / Status / RestartRouter / RestartWorker.
 * 
 * Secrets: the supervisor never holds secret values directly. When building
 * child process args it resolves secrets from the keyring (router/apikey for
 * --api-key, mtls/cert + mtls/key for --mtls-cert/--mtls-key) and never logs
 * them. Dev mode (the default) requires no secrets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * IsRouterRunning reports whether the router child is alive.
 */
export function IsRouterRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(163630674);
}

/**
 * IsWorkerRunning reports whether the worker child is alive.
 */
export function IsWorkerRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3020673067);
}

/**
 * RestartRouter stops then starts the router.
 */
export function RestartRouter(): $CancellablePromise<void> {
    return $Call.ByID(2573138224);
}

/**
 * RestartWorker stops then starts the worker.
 */
export function RestartWorker(): $CancellablePromise<void> {
    return $Call.ByID(1439454907);
}

/**
 * StartRouter launches the router binary from the saved config. It resolves
 * secrets from the keyring only when running in prod mode; dev mode needs none.
 */
export function StartRouter(): $CancellablePromise<void> {
    return $Call.ByID(3710000223);
}

/**
 * StartWorker launches the worker binary from the saved config.
 */
export function StartWorker(): $CancellablePromise<void> {
    return $Call.ByID(286835744);
}

/**
 * Status reports the current state of both supervised children plus a live
 * health probe against the router (which also yields the worker-registration
 * list). It never errors: an unreachable router simply reads as unhealthy.
 */
export function Status(): $CancellablePromise<$models.SupervisorStatus> {
    return $Call.ByID(3064718224);
}

/**
 * StopAll stops both children and removes temp files. Intended for use on
 * application shutdown.
 */
export function StopAll(): $CancellablePromise<void> {
    return $Call.ByID(3237043877);
}

/**
 * StopRouter stops the router child (graceful SIGTERM → SIGKILL). Returns nil
 * if the router was not running.
 */
export function StopRouter(): $CancellablePromise<void> {
    return $Call.ByID(3674121687);
}

/**
 * StopWorker stops the worker child. Returns nil if not running.
 */
export function StopWorker(): $CancellablePromise<void> {
    return $Call.ByID(2057410952);
}
